<a href="https://colab.research.google.com/github/munizgui/CP2_SEM2_SERS/blob/main/1CCA_ML_v0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Exemplo de treinamento e avaliação de um modelo preditivo de classificação

# Preparação do ambiente

In [18]:
import pandas

# Ferramentas para Gráficos
import matplotlib.pyplot as plt
import seaborn as sns

# Ferramentas para Modelagem (utilizar 3 algoritmos do sklearn)

# Separação de dados de treinamento e teste
from sklearn.model_selection import train_test_split

# Algoritmos para classificação:
# Regreção logistica
from sklearn.linear_model import LogisticRegression
# Naive Bayes
from sklearn.naive_bayes import GaussianNB
# Decision Tree
from sklearn.tree import DecisionTreeClassifier

# Avaliação dos modelos
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

# Carga dos dados

In [19]:
# Adicionar o github para que ele nao fique puxando aqui, e sim todos os arquivos lá
dados = pd.read_csv('http://raw.githubusercontent.com/munizgui/CP2_SEM2_SERS/refs/heads/main/csv/Data_for_UCI_named.csv')

# Análise exploratória

In [20]:
dados.head()

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stab,stabf
0,2.959060,3.079885,8.381025,9.780754,3.763085,-0.782604,-1.257395,-1.723086,0.650456,0.859578,0.887445,0.958034,0.055347,unstable
1,9.304097,4.902524,3.047541,1.369357,5.067812,-1.940058,-1.872742,-1.255012,0.413441,0.862414,0.562139,0.781760,-0.005957,stable
2,8.971707,8.848428,3.046479,1.214518,3.405158,-1.207456,-1.277210,-0.920492,0.163041,0.766689,0.839444,0.109853,0.003471,unstable
3,0.716415,7.669600,4.486641,2.340563,3.963791,-1.027473,-1.938944,-0.997374,0.446209,0.976744,0.929381,0.362718,0.028871,unstable
4,3.134112,7.608772,4.943759,9.857573,3.525811,-1.125531,-1.845975,-0.554305,0.797110,0.455450,0.656947,0.820923,0.049860,unstable

In [21]:
dados.describe()

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stab
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,5.250000,5.250001,5.250004,5.249997,3.750000,-1.250000,-1.250000,-1.250000,0.525000,0.525000,0.525000,0.525000,0.015731
std,2.742548,2.742549,2.742549,2.742556,0.752160,0.433035,0.433035,0.433035,0.274256,0.274255,0.274255,0.274255,0.036919
min,0.500793,0.500141,0.500788,0.500473,1.582590,-1.999891,-1.999945,-1.999926,0.050009,0.050053,0.050054,0.050028,-0.080760
25%,2.874892,2.875140,2.875522,2.874950,3.218300,-1.624901,-1.625025,-1.624960,0.287521,0.287552,0.287514,0.287494,-0.015557
50%,5.250004,5.249981,5.249979,5.249734,3.751025,-1.249966,-1.249974,-1.250007,0.525009,0.525003,0.525015,0.525002,0.017142
75%,7.624690,7.624893,7.624948,7.624838,4.282420,-0.874977,-0.875043,-0.875065,0.762435,0.762490,0.762440,0.762433,0.044878
max,9.999469,9.999837,9.999450,9.999443,5.864418,-0.500108,-0.500072,-0.500025,0.999937,0.999944,0.999982,0.999930,0.109403

In [22]:
# Estastísticas de colunas categóricas
dados.describe(include='object')

           stabf
count      10000
unique         2
top     unstable
freq        6380

In [23]:
# Lista das categorias/classes da coluna alvo
dados['stabf'].unique()

array(['unstable', 'stable'], dtype=object)

In [24]:
# COntagem das categorias da coluna 'stabf' (coluna alvo --> target)
dados['stabf'].value_counts()

stabf
unstable    6380
stable      3620
Name: count, dtype: int64

In [25]:
# Definição de dados de entrada (Features/Variaveis Independentes)
# E dados de saida (Target/Variável Dependente)
# X (maiúsculo) ---> entrada
# y (minúsculo) ---> saída

In [26]:
X = dados.drop(columns=['stab', 'stabf'])
y = dados['stabf']

In [27]:
type(X)

pandas.core.frame.DataFrame

In [28]:
X

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4
0,2.959060,3.079885,8.381025,9.780754,3.763085,-0.782604,-1.257395,-1.723086,0.650456,0.859578,0.887445,0.958034
1,9.304097,4.902524,3.047541,1.369357,5.067812,-1.940058,-1.872742,-1.255012,0.413441,0.862414,0.562139,0.781760
2,8.971707,8.848428,3.046479,1.214518,3.405158,-1.207456,-1.277210,-0.920492,0.163041,0.766689,0.839444,0.109853
3,0.716415,7.669600,4.486641,2.340563,3.963791,-1.027473,-1.938944,-0.997374,0.446209,0.976744,0.929381,0.362718
4,3.134112,7.608772,4.943759,9.857573,3.525811,-1.125531,-1.845975,-0.554305,0.797110,0.455450,0.656947,0.820923
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2.930406,9.487627,2.376523,6.187797,3.343416,-0.658054,-1.449106,-1.236256,0.601709,0.779642,0.813512,0.608385
9996,3.392299,1.274827,2.954947,6.894759,4.349512,-1.663661,-0.952437,-1.733414,0.502079,0.567242,0.285880,0.366120
9997,2.364034,2.842030,8.776391,1.008906,4.299976,-1.380719,-0.943884,-1.975373,0.487838,0.986505,0.149286,0.145984
9998,9.631511,3.994398,2.757071,7.821347,2.514755,-0.966330,-0.649915,-0.898510,0.365246,0.587558,0.889118,0.818391
9999,6.530527,6.781790,4.349695,8.673138,3.492807,-1.390285,-1.532193,-0.570329,0.073056,0.505441,0.378761,0.942631

In [29]:
type(y)

pandas.core.series.Series

In [30]:
y

0       unstable
1         stable
2       unstable
3       unstable
4       unstable
          ...
9995    unstable
9996      stable
9997      stable
9998    unstable
9999    unstable
Name: stabf, Length: 10000, dtype: object

# Separação de dados de treinamento e teste

X_train,X_test, y_train, y_test

In [31]:
# SEED ---> random_state ---> parâmetro para "fixar" a amostra
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=1)

In [32]:
# Instanciado o primeiro (LogisticRegression)
modelo_LR = LogisticRegression()

In [33]:
# Treinamento do modelo
modelo_LR.fit(X_train, y_train)

LogisticRegression()

In [36]:
# Geração de probabilidades
probabilidades = modelo_LR.predict_proba(X_test)
probabilidades[:50]

array([[0.03825818, 0.96174182],
       [0.18760004, 0.81239996],
       [0.85964922, 0.14035078],
       [0.8889158 , 0.1110842 ],
       [0.02299536, 0.97700464],
       [0.9086316 , 0.0913684 ],
       [0.07714869, 0.92285131],
       [0.10140089, 0.89859911],
       [0.19258966, 0.80741034],
       [0.92089189, 0.07910811],
       [0.02648338, 0.97351662],
       [0.96382519, 0.03617481],
       [0.17703937, 0.82296063],
       [0.84515051, 0.15484949],
       [0.05981379, 0.94018621],
       [0.30590534, 0.69409466],
       [0.42881637, 0.57118363],
       [0.02138358, 0.97861642],
       [0.77277877, 0.22722123],
       [0.38408291, 0.61591709],
       [0.25730871, 0.74269129],
       [0.21253236, 0.78746764],
       [0.01101105, 0.98898895],
       [0.55511496, 0.44488504],
       [0.5941227 , 0.4058773 ],
       [0.03729827, 0.96270173],
       [0.03018877, 0.96981123],
       [0.81818048, 0.18181952],
       [0.08051674, 0.91948326],
       [0.21380298, 0.78619702],
       [0.01446423, 0.98553577],
       [0.15555293, 0.84444707],
       [0.00701303, 0.99298697],
       [0.73311779, 0.26688221],
       [0.09443286, 0.90556714],
       [0.23768152, 0.76231848],
       [0.00245149, 0.99754851],
       [0.19188677, 0.80811323],
       [0.03911135, 0.96088865],
       [0.67240299, 0.32759701],
       [0.00291961, 0.99708039],
       [0.07411817, 0.92588183],
       [0.09051384, 0.90948616],
       [0.0144238 , 0.9855762 ],
       [0.8801446 , 0.1198554 ],
       [0.35307888, 0.64692112],
       [0.00370904, 0.99629096],
       [0.00304941, 0.99695059],
       [0.94153892, 0.05846108],
       [0.00903501, 0.99096499]])

In [37]:
# Geração de previsões
y_predict = modelo_LR.predict(X_test)
y_predict[:50]

array(['unstable', 'unstable', 'stable', 'stable', 'unstable', 'stable',
       'unstable', 'unstable', 'unstable', 'stable', 'unstable', 'stable',
       'unstable', 'stable', 'unstable', 'unstable', 'unstable',
       'unstable', 'stable', 'unstable', 'unstable', 'unstable',
       'unstable', 'stable', 'stable', 'unstable', 'unstable', 'stable',
       'unstable', 'unstable', 'unstable', 'unstable', 'unstable',
       'stable', 'unstable', 'unstable', 'unstable', 'unstable',
       'unstable', 'stable', 'unstable', 'unstable', 'unstable',
       'unstable', 'stable', 'unstable', 'unstable', 'unstable', 'stable',
       'unstable'], dtype=object)

In [35]:
# Avaliação do modelo
'''
Gerar comandos para as métricas do modelo treinado usando seaborn e matplotlib.
Crie gráficos auxiliares e tabelas contendo todas as métricas que importamos na celula inicial.
Incluindo classification report.
'''

'\nGerar comandos para as métricas do modelo treinado usando seaborn e matplotlib.\nCrie gráficos auxiliares e tabelas contendo todas as métricas que importamos na celula inicial.\nIncluindo classification report.\n'